// AUTO-GENERATED by `bun run tools/license-mint/keygen.ts`.
// Replace this file's contents by running the keygen script once on your own
// PC. Ship the resulting file inside the app; keep the matching private.key
// on your machine (and a USB backup). Never commit private.key.
//
// While this placeholder is in place, the app treats every license key as
// invalid — meaning: build the app for the FIRST time only AFTER running
// keygen once. The trial still works either way.

export const LICENSE_PUBLIC_KEY_HEX = "";
