// Generates a fresh Ed25519 keypair for license minting.
//
// Run once, on your own PC:
//     bun run tools/license-mint/keygen.ts
//
// Writes:
//   tools/license-mint/private.key   (KEEP SECRET — DO NOT COMMIT)
//   src/lib/license/public-key.ts    (safe to commit; baked into the app)
//
// ─────────────────────────────────────────────────────────────────────
// ROTATING KEYS (emergency only — e.g. private.key was leaked/stolen):
//   This script NEVER overwrites an existing private.key on its own.
//   To force a brand-new keypair (which invalidates EVERY license ever
//   issued and requires re-minting for all legitimate customers):
//     1. Manually delete tools/license-mint/private.key
//     2. Run this script again → fresh keypair is generated
//     3. Rebuild the app (bun run tauri build)
//     4. Re-mint and re-send keys to all your customers
//   In normal use you should NEVER need to do this. Keep private.key
//   safe (USB backup) and this script is idempotent — safe to re-run
//   before every build.
// ─────────────────────────────────────────────────────────────────────


import * as ed from "@noble/ed25519";
import { existsSync, writeFileSync, readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createInterface } from "node:readline/promises";
import { stdin, stdout } from "node:process";

const HERE = dirname(fileURLToPath(import.meta.url));
const PRIVATE_KEY_PATH = join(HERE, "private.key");
const PUBLIC_KEY_TS = join(HERE, "..", "..", "src", "lib", "license", "public-key.ts");

function toHex(bytes: Uint8Array): string {
  return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}

async function main() {
  if (existsSync(PRIVATE_KEY_PATH)) {
    const rl = createInterface({ input: stdin, output: stdout });
    const ans = await rl.question(
      `\n⚠  private.key already exists at ${PRIVATE_KEY_PATH}\n` +
      `   Overwriting invalidates every license you've ever issued.\n` +
      `   Type "yes" to overwrite, anything else to abort: `,
    );
    rl.close();
    if (ans.trim().toLowerCase() !== "yes") {
      console.log("Aborted. No files changed.");
      return;
    }
  }

  const priv = ed.utils.randomSecretKey();
  const pub = await ed.getPublicKeyAsync(priv);

  writeFileSync(PRIVATE_KEY_PATH, toHex(priv) + "\n", { mode: 0o600 });

  const banner = `// AUTO-GENERATED by tools/license-mint/keygen.ts on ${new Date().toISOString()}.
// Safe to commit. Regenerating this file (via keygen) invalidates every
// license issued with the previous key — do so only intentionally.
`;
  const body = `\nexport const LICENSE_PUBLIC_KEY_HEX = "${toHex(pub)}";\n`;
  writeFileSync(PUBLIC_KEY_TS, banner + body);

  console.log("\n✔ Keypair generated.");
  console.log(`   Private key → ${PRIVATE_KEY_PATH}  (KEEP SECRET, BACK UP TO USB)`);
  console.log(`   Public key  → ${PUBLIC_KEY_TS}   (commit this)`);
  console.log("\nNext: run tools/license-mint/mint.ts to issue a license key.");

  // Sanity check
  const check = readFileSync(PUBLIC_KEY_TS, "utf8");
  if (!check.includes(toHex(pub))) {
    console.error("Public key file did not write correctly. Aborting.");
    process.exit(1);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
