// Extended HSN/SAC master supplement — appended to HSN_MASTER_DATASET.
// Codes here fill gaps in the primary seed so the autocomplete dropdown
// surfaces many more common Indian trade & service codes.
// Rates are the standard published GST slabs; edit as CBIC notifications change.

import type { HsnSeedItem } from "./seedHsnData";

const R0 = { cgst: 0, sgst: 0, igst: 0 };
const R5 = { cgst: 2.5, sgst: 2.5, igst: 5 };
const R12 = { cgst: 6, sgst: 6, igst: 12 };
const R18 = { cgst: 9, sgst: 9, igst: 18 };
const R28 = { cgst: 14, sgst: 14, igst: 28 };

export const HSN_EXTENDED_DATASET: HsnSeedItem[] = [
  // === Chapter 02/03 — Meat & Fish ===
  { code: "0201", desc: "Meat of bovine animals, fresh or chilled", ...R0 },
  { code: "0207", desc: "Meat & edible offal of poultry, fresh/chilled/frozen", ...R0 },
  { code: "0302", desc: "Fish, fresh or chilled (excl. fillets)", ...R0 },
  { code: "0303", desc: "Fish, frozen (excl. fillets)", ...R0 },
  { code: "0306", desc: "Crustaceans (shrimp, prawns, lobster) fresh/frozen", ...R5 },

  // === Chapter 04 — Dairy extras ===
  { code: "0405", desc: "Butter and other fats derived from milk", ...R12 },
  { code: "0408", desc: "Birds' eggs, not in shell; egg yolks", ...R5 },

  // === Chapter 07 — Vegetables extras ===
  { code: "0702", desc: "Tomatoes, fresh or chilled", ...R0 },
  { code: "0704", desc: "Cabbages, cauliflowers, kohlrabi, kale", ...R0 },
  { code: "0705", desc: "Lettuce and chicory, fresh or chilled", ...R0 },
  { code: "0706", desc: "Carrots, turnips, salad beetroot, radishes", ...R0 },
  { code: "0707", desc: "Cucumbers and gherkins, fresh or chilled", ...R0 },
  { code: "0708", desc: "Leguminous vegetables, fresh or chilled", ...R0 },
  { code: "0710", desc: "Vegetables (uncooked or steamed) frozen", ...R5 },
  { code: "0712", desc: "Dried vegetables, whole/cut/sliced/powdered", ...R5 },
  { code: "0714", desc: "Manioc, arrowroot, sweet potatoes, tapioca", ...R5 },

  // === Chapter 08 — Fruits extras ===
  { code: "0801", desc: "Coconuts, Brazil nuts, cashew nuts, fresh/dried", ...R5 },
  { code: "0802", desc: "Other nuts (almonds, walnuts, pistachios) fresh/dried", ...R12 },
  { code: "0804", desc: "Dates, figs, pineapples, avocados, guavas, mangoes", ...R5 },
  { code: "0806", desc: "Grapes, fresh or dried (raisins)", ...R5 },
  { code: "0807", desc: "Melons, watermelons, papayas, fresh", ...R0 },
  { code: "0808", desc: "Apples, pears and quinces, fresh", ...R0 },
  { code: "0809", desc: "Apricots, cherries, peaches, plums, fresh", ...R0 },
  { code: "0810", desc: "Other fruit (strawberries, kiwi, pomegranate) fresh", ...R0 },
  { code: "0813", desc: "Dried fruit (excl. that of 0801-0806); mixed nuts", ...R12 },

  // === Chapter 09 — Coffee, Tea, Spices extras ===
  { code: "0903", desc: "Mate", ...R5 },
  { code: "0905", desc: "Vanilla", ...R5 },
  { code: "0906", desc: "Cinnamon and cinnamon-tree flowers", ...R5 },
  { code: "0907", desc: "Cloves (whole fruit, cloves and stems)", ...R5 },
  { code: "0909", desc: "Seeds of anise, coriander, cumin, caraway, fennel", ...R5 },
  { code: "0911", desc: "Turmeric (haldi), fresh", ...R0 },
  { code: "0913", desc: "Mixed spices, curry powder", ...R5 },

  // === Chapter 10 — Cereals extras ===
  { code: "1002", desc: "Rye", ...R0 },
  { code: "1003", desc: "Barley", ...R0 },
  { code: "1004", desc: "Oats", ...R0 },
  { code: "1005", desc: "Maize (corn)", ...R0 },
  { code: "1007", desc: "Grain sorghum (jowar)", ...R0 },
  { code: "1008", desc: "Buckwheat, millet, canary seed (bajra, ragi)", ...R0 },

  // === Chapter 11 — Flours ===
  { code: "1103", desc: "Cereal groats, meal and pellets", ...R5 },
  { code: "1104", desc: "Cereal grains otherwise worked (rolled/flaked)", ...R5 },
  { code: "1105", desc: "Flour, meal, powder, flakes of potatoes", ...R5 },
  { code: "1106", desc: "Flour of dried leguminous vegetables (besan)", ...R5 },
  { code: "1108", desc: "Starches; inulin", ...R12 },
  { code: "1109", desc: "Wheat gluten, whether or not dried", ...R5 },

  // === Chapter 12 — Oil seeds ===
  { code: "1201", desc: "Soya beans, whether or not broken", ...R5 },
  { code: "1202", desc: "Ground-nuts, not roasted", ...R5 },
  { code: "1207", desc: "Other oil seeds and oleaginous fruits", ...R5 },
  { code: "1211", desc: "Plants & parts used in perfumery/pharmacy", ...R5 },
  { code: "1212", desc: "Locust beans, seaweeds, sugar beet, sugar cane", ...R5 },

  // === Chapter 13 — Gums, resins ===
  { code: "1301", desc: "Lac; natural gums, resins, gum-resins, oleoresins", ...R5 },
  { code: "1302", desc: "Vegetable saps and extracts", ...R18 },

  // === Chapter 14 — Vegetable plaiting ===
  { code: "1401", desc: "Vegetable materials for plaiting (bamboo, rattan)", ...R5 },
  { code: "1404", desc: "Vegetable products n.e.c. (bidi wrapper leaves, etc.)", ...R5 },

  // === Chapter 15 — Fats & oils extras ===
  { code: "1508", desc: "Ground-nut oil and its fractions", ...R5 },
  { code: "1513", desc: "Coconut, palm kernel, babassu oil", ...R5 },
  { code: "1514", desc: "Rape, colza or mustard oil", ...R5 },
  { code: "1516", desc: "Animal/vegetable fats hydrogenated, refined", ...R5 },
  { code: "1518", desc: "Animal/vegetable fats chemically modified", ...R18 },
  { code: "1520", desc: "Glycerol, crude; glycerol waters and lyes", ...R18 },

  // === Chapter 16 — Meat/fish preparations ===
  { code: "1601", desc: "Sausages and similar products of meat", ...R12 },
  { code: "1602", desc: "Other prepared or preserved meat", ...R12 },
  { code: "1604", desc: "Prepared or preserved fish; caviar", ...R12 },
  { code: "1605", desc: "Crustaceans, molluscs prepared or preserved", ...R12 },

  // === Chapter 17 — Sugar extras ===
  { code: "1703", desc: "Molasses resulting from extraction of sugar", ...R18 },

  // === Chapter 18 — Cocoa extras ===
  { code: "1803", desc: "Cocoa paste, whether or not defatted", ...R18 },
  { code: "1804", desc: "Cocoa butter, fat and oil", ...R18 },
  { code: "1805", desc: "Cocoa powder, not containing added sugar", ...R18 },

  // === Chapter 19 — Cereal preparations extras ===
  { code: "1903", desc: "Tapioca and substitutes prepared from starch", ...R5 },

  // === Chapter 20 — Preparations of fruit/vegetables ===
  { code: "2001", desc: "Vegetables/fruit preserved by vinegar or acetic acid", ...R12 },
  { code: "2002", desc: "Tomatoes prepared or preserved otherwise", ...R12 },
  { code: "2003", desc: "Mushrooms and truffles prepared or preserved", ...R12 },
  { code: "2004", desc: "Other vegetables prepared or preserved, frozen", ...R12 },
  { code: "2006", desc: "Vegetables/fruit preserved by sugar (glacé)", ...R12 },
  { code: "2007", desc: "Jams, fruit jellies, marmalades, purées, pastes", ...R12 },
  { code: "2008", desc: "Fruit, nuts otherwise prepared or preserved", ...R12 },
  { code: "2009", desc: "Fruit juices (including grape must), unfermented", ...R12 },

  // === Chapter 21 — Miscellaneous edible preparations extras ===
  { code: "2101", desc: "Extracts, essences of coffee, tea, mate; chicory", ...R18 },
  { code: "2102", desc: "Yeasts; single-cell micro-organisms", ...R12 },
  { code: "2105", desc: "Ice cream and other edible ice", ...R18 },

  // === Chapter 22 — Beverages extras ===
  { code: "2204", desc: "Wine of fresh grapes (State excise, GST NA)", ...R0 },
  { code: "2205", desc: "Vermouth and other wine of fresh grapes", ...R0 },
  { code: "2206", desc: "Other fermented beverages (cider, perry, mead)", ...R0 },
  { code: "2208", desc: "Undenatured ethyl alcohol < 80% (State excise)", ...R0 },
  { code: "2209", desc: "Vinegar and substitutes for vinegar", ...R18 },

  // === Chapter 23 — Residues, animal feed ===
  { code: "2301", desc: "Flours, meals and pellets of meat/fish, unfit for humans", ...R5 },
  { code: "2302", desc: "Bran, sharps and other residues of cereal milling", ...R0 },
  { code: "2303", desc: "Residues of starch manufacture; brewing dregs", ...R5 },
  { code: "2304", desc: "Oil-cake and other solid residues of soya-bean oil", ...R0 },
  { code: "2306", desc: "Oil-cake from vegetable fats/oils (excl. 2304/05)", ...R0 },
  { code: "2309", desc: "Preparations for animal feeding (cattle feed)", ...R0 },

  // === Chapter 25 — Salt, minerals ===
  { code: "2503", desc: "Sulphur of all kinds, other than sublimed", ...R5 },
  { code: "2505", desc: "Natural sands (silica, quartz) of all kinds", ...R5 },
  { code: "2506", desc: "Quartz (other than natural sands); quartzite", ...R5 },
  { code: "2515", desc: "Marble, travertine, ecaussine (crude)", ...R12 },
  { code: "2516", desc: "Granite, porphyry, basalt, sandstone (crude)", ...R5 },
  { code: "2517", desc: "Pebbles, gravel, broken stone, macadam", ...R5 },
  { code: "2521", desc: "Limestone flux; limestone for lime or cement", ...R5 },
  { code: "2522", desc: "Quicklime, slaked lime and hydraulic lime", ...R5 },
  { code: "2524", desc: "Asbestos", ...R18 },

  // === Chapter 27 — Fuels ===
  { code: "2701", desc: "Coal; briquettes, ovoids and similar solid fuels", ...R5 },
  { code: "2702", desc: "Lignite, whether or not agglomerated", ...R5 },
  { code: "2704", desc: "Coke and semi-coke of coal, lignite or peat", ...R5 },
  { code: "2713", desc: "Petroleum coke, bitumen and other residues", ...R18 },
  { code: "2715", desc: "Bituminous mixtures based on natural asphalt", ...R18 },

  // === Chapter 28 — Inorganic chemicals ===
  { code: "2801", desc: "Fluorine, chlorine, bromine and iodine", ...R18 },
  { code: "2804", desc: "Hydrogen, rare gases and other non-metals", ...R18 },
  { code: "2806", desc: "Hydrogen chloride; chlorosulphuric acid", ...R18 },
  { code: "2807", desc: "Sulphuric acid; oleum", ...R18 },
  { code: "2808", desc: "Nitric acid; sulphonitric acids", ...R18 },
  { code: "2809", desc: "Diphosphorus pentoxide; phosphoric acid", ...R18 },
  { code: "2814", desc: "Ammonia, anhydrous or in aqueous solution", ...R18 },
  { code: "2815", desc: "Sodium hydroxide (caustic soda); potassium hydroxide", ...R18 },
  { code: "2823", desc: "Titanium oxides", ...R18 },
  { code: "2827", desc: "Chlorides, chloride oxides and chloride hydroxides", ...R18 },
  { code: "2829", desc: "Chlorates and perchlorates; bromates; iodates", ...R18 },

  // === Chapter 29 — Organic chemicals ===
  { code: "2901", desc: "Acyclic hydrocarbons", ...R18 },
  { code: "2902", desc: "Cyclic hydrocarbons (benzene, toluene, xylenes)", ...R18 },
  { code: "2905", desc: "Acyclic alcohols and their derivatives", ...R18 },
  { code: "2907", desc: "Phenols; phenol-alcohols", ...R18 },
  { code: "2915", desc: "Saturated acyclic monocarboxylic acids (acetic, formic)", ...R18 },
  { code: "2916", desc: "Unsaturated acyclic monocarboxylic acids", ...R18 },
  { code: "2922", desc: "Oxygen-function amino-compounds", ...R18 },
  { code: "2929", desc: "Compounds with other nitrogen function", ...R18 },
  { code: "2941", desc: "Antibiotics", ...R5 },

  // === Chapter 30 — Pharma extras ===
  { code: "3001", desc: "Glands and other organs for organo-therapeutic uses", ...R5 },
  { code: "3002", desc: "Human blood; animal blood; vaccines, toxins", ...R5 },
  { code: "3005", desc: "Wadding, gauze, bandages and similar (dressings)", ...R12 },
  { code: "3006", desc: "Pharmaceutical goods (sutures, first-aid boxes)", ...R12 },

  // === Chapter 31 — Fertilizers ===
  { code: "3101", desc: "Animal or vegetable fertilisers (bio-manure)", ...R5 },
  { code: "3102", desc: "Mineral or chemical fertilisers, nitrogenous (urea)", ...R5 },
  { code: "3103", desc: "Mineral or chemical fertilisers, phosphatic", ...R5 },
  { code: "3104", desc: "Mineral or chemical fertilisers, potassic", ...R5 },

  // === Chapter 32 — Paints, dyes ===
  { code: "3201", desc: "Tanning extracts of vegetable origin", ...R18 },
  { code: "3203", desc: "Colouring matter of vegetable or animal origin", ...R18 },
  { code: "3204", desc: "Synthetic organic colouring matter", ...R18 },
  { code: "3205", desc: "Colour lakes and preparations based thereon", ...R18 },
  { code: "3206", desc: "Other colouring matter; inorganic pigments", ...R18 },
  { code: "3212", desc: "Pigments dispersed in non-aqueous media", ...R18 },
  { code: "3214", desc: "Glaziers' putty, resin cements, caulking compounds", ...R18 },
  { code: "3215", desc: "Printing ink, writing/drawing ink and other inks", ...R18 },

  // === Chapter 33 — Cosmetics extras ===
  { code: "3301", desc: "Essential oils; resinoids; aqueous distillates", ...R18 },
  { code: "3302", desc: "Mixtures of odoriferous substances (flavour, fragrance)", ...R18 },
  { code: "3303", desc: "Perfumes and toilet waters", ...R18 },

  // === Chapter 34 — Soaps extras ===
  { code: "3403", desc: "Lubricating preparations", ...R18 },
  { code: "3404", desc: "Artificial waxes and prepared waxes", ...R18 },
  { code: "3405", desc: "Polishes and creams for footwear, furniture, metal", ...R18 },
  { code: "3407", desc: "Modelling pastes; dental waxes; dental impression compounds", ...R18 },

  // === Chapter 35 — Albuminoids ===
  { code: "3501", desc: "Casein, caseinates and other casein derivatives", ...R18 },
  { code: "3502", desc: "Albumins; albuminates and albumin derivatives", ...R18 },
  { code: "3503", desc: "Gelatin and gelatin derivatives", ...R18 },
  { code: "3505", desc: "Dextrins and other modified starches; glues", ...R18 },
  { code: "3507", desc: "Enzymes; prepared enzymes n.e.c.", ...R18 },

  // === Chapter 36 — Explosives, matches ===
  { code: "3601", desc: "Propellent powders", ...R18 },
  { code: "3602", desc: "Prepared explosives, other than propellent powders", ...R18 },
  { code: "3605", desc: "Matches, other than pyrotechnic articles of 3604", ...R12 },

  // === Chapter 37 — Photographic ===
  { code: "3701", desc: "Photographic plates and film in the flat, sensitised", ...R18 },
  { code: "3707", desc: "Chemical preparations for photographic uses", ...R18 },

  // === Chapter 38 — Miscellaneous chemicals ===
  { code: "3802", desc: "Activated carbon; activated natural mineral products", ...R18 },
  { code: "3809", desc: "Finishing agents, dye carriers, textile aux. products", ...R18 },
  { code: "3810", desc: "Pickling preparations; soldering, brazing, welding powders", ...R18 },
  { code: "3814", desc: "Organic composite solvents and thinners; paint removers", ...R18 },
  { code: "3819", desc: "Hydraulic brake fluids", ...R18 },
  { code: "3820", desc: "Anti-freezing preparations and prepared de-icing fluids", ...R18 },
  { code: "3824", desc: "Prepared binders for foundry moulds/cores; chemical products n.e.c.", ...R18 },
  { code: "3826", desc: "Biodiesel and mixtures thereof (not petroleum)", ...R12 },

  // === Chapter 39 — Plastics extras ===
  { code: "3901", desc: "Polymers of ethylene, in primary forms", ...R18 },
  { code: "3902", desc: "Polymers of propylene or other olefins", ...R18 },
  { code: "3903", desc: "Polymers of styrene, in primary forms", ...R18 },
  { code: "3904", desc: "Polymers of vinyl chloride (PVC), in primary forms", ...R18 },
  { code: "3907", desc: "Polyacetals, polyethers, epoxide resins", ...R18 },
  { code: "3915", desc: "Waste, parings and scrap, of plastics", ...R5 },
  { code: "3917", desc: "Tubes, pipes and hoses of plastics", ...R18 },
  { code: "3919", desc: "Self-adhesive plates, sheets, film, tape of plastics", ...R18 },
  { code: "3920", desc: "Other plates, sheets, film, foil and strip of plastics", ...R18 },
  { code: "3921", desc: "Other plates, sheets, film, foil and strip of plastics", ...R18 },
  { code: "3922", desc: "Baths, wash-basins, sanitary ware of plastics", ...R18 },
  { code: "3923", desc: "Articles for conveyance/packing of plastics (bottles, boxes)", ...R18 },
  { code: "3924", desc: "Tableware, kitchenware, household articles of plastics", ...R18 },
  { code: "3925", desc: "Builders' ware of plastics n.e.c.", ...R18 },
  { code: "3926", desc: "Other articles of plastics", ...R18 },

  // === Chapter 40 — Rubber ===
  { code: "4001", desc: "Natural rubber, balata, gutta-percha", ...R5 },
  { code: "4002", desc: "Synthetic rubber and factice derived from oils", ...R18 },
  { code: "4005", desc: "Compounded rubber, unvulcanised, in primary forms", ...R18 },
  { code: "4008", desc: "Plates, sheets, strip, rods of vulcanised rubber", ...R18 },
  { code: "4011", desc: "New pneumatic tyres, of rubber", ...R28 },
  { code: "4013", desc: "Inner tubes, of rubber", ...R28 },
  { code: "4016", desc: "Other articles of vulcanised rubber (other than hard)", ...R18 },

  // === Chapter 41-43 — Leather / Fur ===
  { code: "4101", desc: "Raw hides and skins of bovine or equine animals", ...R5 },
  { code: "4104", desc: "Tanned or crust hides and skins of bovine or equine", ...R5 },
  { code: "4107", desc: "Leather further prepared after tanning", ...R12 },
  { code: "4202", desc: "Trunks, suit-cases, brief-cases, handbags, wallets", ...R18 },
  { code: "4203", desc: "Articles of apparel and clothing accessories of leather", ...R12 },
  { code: "4302", desc: "Tanned or dressed furskins", ...R18 },

  // === Chapter 44 — Wood ===
  { code: "4401", desc: "Fuel wood, in logs, billets, twigs; wood chips", ...R5 },
  { code: "4403", desc: "Wood in the rough, whether or not stripped of bark", ...R18 },
  { code: "4407", desc: "Wood sawn or chipped lengthwise, sliced or peeled", ...R18 },
  { code: "4410", desc: "Particle board, oriented strand board (OSB)", ...R18 },
  { code: "4411", desc: "Fibreboard of wood or other ligneous materials (MDF)", ...R18 },
  { code: "4412", desc: "Plywood, veneered panels and similar laminated wood", ...R18 },
  { code: "4418", desc: "Builders' joinery and carpentry of wood (doors, windows)", ...R18 },
  { code: "4419", desc: "Tableware and kitchenware, of wood", ...R12 },
  { code: "4420", desc: "Wood marquetry and inlaid wood; caskets, statuettes", ...R12 },
  { code: "4421", desc: "Other articles of wood", ...R12 },

  // === Chapter 48-49 — Paper ===
  { code: "4801", desc: "Newsprint, in rolls or sheets", ...R5 },
  { code: "4802", desc: "Uncoated paper and paperboard, for writing/printing", ...R12 },
  { code: "4803", desc: "Toilet or facial tissue stock, towel or napkin stock", ...R18 },
  { code: "4808", desc: "Paper and paperboard, corrugated", ...R12 },
  { code: "4810", desc: "Paper and paperboard, coated with kaolin", ...R12 },
  { code: "4818", desc: "Toilet paper, tissues, handkerchiefs, table napkins", ...R18 },
  { code: "4819", desc: "Cartons, boxes, cases, bags of paper/paperboard", ...R18 },
  { code: "4820", desc: "Registers, account books, note books, exercise books", ...R12 },
  { code: "4821", desc: "Paper or paperboard labels of all kinds", ...R18 },
  { code: "4823", desc: "Other paper, paperboard, cellulose wadding articles", ...R18 },
  { code: "4901", desc: "Printed books, brochures, leaflets", ...R0 },
  { code: "4902", desc: "Newspapers, journals & periodicals", ...R0 },
  { code: "4905", desc: "Maps and hydrographic charts of all kinds, printed", ...R0 },
  { code: "4907", desc: "Unused postage, revenue stamps; cheque forms", ...R0 },
  { code: "4909", desc: "Printed or illustrated postcards; greeting cards", ...R12 },
  { code: "4910", desc: "Calendars of any kind, printed", ...R12 },
  { code: "4911", desc: "Other printed matter (posters, catalogues)", ...R12 },

  // === Chapter 50-55 — Textiles extras ===
  { code: "5001", desc: "Silk-worm cocoons suitable for reeling", ...R5 },
  { code: "5002", desc: "Raw silk (not thrown)", ...R5 },
  { code: "5007", desc: "Woven fabrics of silk or of silk waste", ...R5 },
  { code: "5101", desc: "Wool, not carded or combed", ...R5 },
  { code: "5106", desc: "Yarn of carded wool, not for retail sale", ...R5 },
  { code: "5111", desc: "Woven fabrics of carded wool", ...R5 },
  { code: "5201", desc: "Cotton, not carded or combed", ...R5 },
  { code: "5203", desc: "Cotton, carded or combed", ...R5 },
  { code: "5205", desc: "Cotton yarn (85% or more cotton), not for retail", ...R5 },
  { code: "5209", desc: "Woven fabrics of cotton (85%+), > 200 g/m²", ...R5 },
  { code: "5210", desc: "Woven fabrics of cotton mixed with man-made fibres", ...R5 },
  { code: "5211", desc: "Woven fabrics of cotton, mixed, > 200 g/m²", ...R5 },
  { code: "5309", desc: "Woven fabrics of flax (linen)", ...R5 },
  { code: "5401", desc: "Sewing thread of man-made filaments", ...R12 },
  { code: "5402", desc: "Synthetic filament yarn (not for retail sale)", ...R12 },
  { code: "5408", desc: "Woven fabrics of artificial filament yarn", ...R5 },
  { code: "5501", desc: "Synthetic filament tow", ...R18 },
  { code: "5503", desc: "Synthetic staple fibres, not carded or combed", ...R18 },
  { code: "5509", desc: "Yarn of synthetic staple fibres (not retail)", ...R12 },
  { code: "5512", desc: "Woven fabrics of synthetic staple fibres (85%+)", ...R5 },
  { code: "5513", desc: "Woven fabrics of synthetic staple fibres < 170 g/m²", ...R5 },
  { code: "5515", desc: "Other woven fabrics of synthetic staple fibres", ...R5 },

  // === Chapter 56-59 — Wadding, carpets, coated ===
  { code: "5601", desc: "Wadding of textile materials; nonwovens; sanitary napkins", ...R12 },
  { code: "5605", desc: "Metallised yarn; textile yarn combined with metal", ...R12 },
  { code: "5607", desc: "Twine, cordage, ropes and cables (jute, coir, plastic)", ...R12 },
  { code: "5608", desc: "Knotted netting of twine; fishing nets", ...R12 },
  { code: "5701", desc: "Carpets & other textile floor coverings, knotted", ...R12 },
  { code: "5703", desc: "Carpets, tufted, whether or not made up", ...R12 },
  { code: "5801", desc: "Woven pile fabrics and chenille fabrics", ...R5 },
  { code: "5802", desc: "Terry towelling; tufted textile fabrics", ...R5 },
  { code: "5806", desc: "Narrow woven fabrics (ribbons, tapes)", ...R5 },
  { code: "5810", desc: "Embroidery in the piece, in strips or in motifs", ...R5 },
  { code: "5903", desc: "Textile fabrics impregnated / coated with plastics", ...R12 },
  { code: "5906", desc: "Rubberised textile fabrics (excl. 5902)", ...R12 },

  // === Chapter 60-63 — Knitted, apparel extras ===
  { code: "6001", desc: "Pile fabrics, including 'long pile' knitted or crocheted", ...R5 },
  { code: "6004", desc: "Knitted or crocheted fabrics of width > 30 cm", ...R5 },
  { code: "6101", desc: "Men's overcoats, car-coats, capes, cloaks (knitted)", ...R12 },
  { code: "6102", desc: "Women's overcoats, car-coats, cloaks (knitted)", ...R12 },
  { code: "6103", desc: "Men's suits, ensembles, jackets, trousers (knitted)", ...R12 },
  { code: "6104", desc: "Women's suits, ensembles, jackets, dresses (knitted)", ...R12 },
  { code: "6105", desc: "Men's shirts, knitted or crocheted", ...R12 },
  { code: "6106", desc: "Women's blouses, shirts, shirt-blouses (knitted)", ...R12 },
  { code: "6107", desc: "Men's underpants, briefs, nightshirts (knitted)", ...R12 },
  { code: "6108", desc: "Women's slips, petticoats, briefs, nightdresses (knitted)", ...R12 },
  { code: "6109", desc: "T-shirts, singlets and other vests, knitted or crocheted", ...R12 },
  { code: "6110", desc: "Jerseys, pullovers, cardigans, waistcoats (knitted)", ...R12 },
  { code: "6111", desc: "Babies' garments and clothing accessories (knitted)", ...R12 },
  { code: "6115", desc: "Panty hose, tights, stockings, socks (knitted)", ...R12 },
  { code: "6116", desc: "Gloves, mittens and mitts, knitted or crocheted", ...R12 },
  { code: "6201", desc: "Men's overcoats, car-coats (not knitted)", ...R12 },
  { code: "6202", desc: "Women's overcoats, car-coats (not knitted)", ...R12 },
  { code: "6204", desc: "Women's suits, ensembles, jackets, dresses (woven)", ...R12 },
  { code: "6206", desc: "Women's blouses, shirts and shirt-blouses (woven)", ...R12 },
  { code: "6207", desc: "Men's singlets, underpants, briefs (woven)", ...R12 },
  { code: "6208", desc: "Women's slips, petticoats, briefs (woven)", ...R12 },
  { code: "6209", desc: "Babies' garments and clothing accessories (woven)", ...R12 },
  { code: "6210", desc: "Garments made up of fabrics of 5602, 5603, 5903, 5906, 5907", ...R12 },
  { code: "6211", desc: "Track suits, ski suits and swim-wear; other garments", ...R12 },
  { code: "6212", desc: "Brassieres, girdles, corsets, braces, suspenders", ...R12 },
  { code: "6214", desc: "Shawls, scarves, mufflers, mantillas, veils", ...R5 },
  { code: "6215", desc: "Ties, bow ties and cravats", ...R12 },
  { code: "6301", desc: "Blankets and travelling rugs", ...R5 },
  { code: "6302", desc: "Bed linen, table linen, toilet linen, kitchen linen", ...R5 },
  { code: "6303", desc: "Curtains (incl. drapes) and interior blinds", ...R12 },
  { code: "6304", desc: "Other furnishing articles (excl. 9404)", ...R12 },
  { code: "6305", desc: "Sacks and bags for packing of goods", ...R5 },
  { code: "6307", desc: "Other made-up textile articles (dusters, masks)", ...R5 },
  { code: "6309", desc: "Worn clothing and other worn textile articles", ...R5 },

  // === Chapter 64 — Footwear extras ===
  { code: "6401", desc: "Waterproof footwear (rubber/plastic uppers)", ...R18 },
  { code: "6402", desc: "Other footwear with outer soles/uppers of rubber/plastics", ...R18 },
  { code: "6403", desc: "Footwear with outer soles of rubber, uppers of leather", ...R18 },
  { code: "6404", desc: "Footwear with outer soles of rubber/plastic, uppers of textiles", ...R18 },
  { code: "6405", desc: "Other footwear", ...R18 },
  { code: "6406", desc: "Parts of footwear; removable insoles, heel cushions", ...R18 },

  // === Chapter 65-67 — Headgear, umbrellas ===
  { code: "6505", desc: "Hats and other headgear, knitted or crocheted", ...R12 },
  { code: "6601", desc: "Umbrellas and sun umbrellas", ...R12 },

  // === Chapter 68-70 — Stone, ceramics, glass ===
  { code: "6802", desc: "Worked monumental or building stone (marble slabs)", ...R18 },
  { code: "6810", desc: "Articles of cement, of concrete or of artificial stone", ...R18 },
  { code: "6815", desc: "Articles of stone or of other mineral substances", ...R18 },
  { code: "6901", desc: "Bricks, blocks, tiles of siliceous fossil meals", ...R5 },
  { code: "6902", desc: "Refractory bricks, blocks, tiles and similar goods", ...R18 },
  { code: "6904", desc: "Ceramic building bricks, flooring blocks", ...R5 },
  { code: "6907", desc: "Ceramic flags and paving, hearth or wall tiles (glazed)", ...R18 },
  { code: "6910", desc: "Ceramic sinks, wash basins, bidets, WC pans", ...R18 },
  { code: "6911", desc: "Tableware, kitchenware of porcelain or china", ...R12 },
  { code: "6912", desc: "Ceramic tableware, kitchenware (other than porcelain)", ...R12 },
  { code: "7003", desc: "Cast glass and rolled glass in sheets or profiles", ...R18 },
  { code: "7005", desc: "Float glass, surface ground or polished, in sheets", ...R18 },
  { code: "7007", desc: "Safety glass, of toughened or laminated glass", ...R18 },
  { code: "7009", desc: "Glass mirrors, whether or not framed", ...R18 },
  { code: "7010", desc: "Carboys, bottles, jars, phials of glass, for packing", ...R18 },
  { code: "7013", desc: "Glassware of a kind used for table, kitchen, toilet", ...R18 },
  { code: "7016", desc: "Paving blocks, bricks, tiles of pressed/moulded glass", ...R18 },
  { code: "7020", desc: "Other articles of glass", ...R18 },

  // === Chapter 71 — Precious metals, jewellery ===
  { code: "7101", desc: "Pearls, natural or cultured (unworked/worked)", ...R0 },
  { code: "7102", desc: "Diamonds, whether or not worked", ...R0 },
  { code: "7103", desc: "Precious/semi-precious stones (excl. diamonds)", ...R0 },
  { code: "7106", desc: "Silver (incl. plated with gold/platinum), unwrought", ...R0 },
  { code: "7108", desc: "Gold (incl. gold plated with platinum), unwrought/semi-mfd", ...R0 },
  { code: "7113", desc: "Articles of jewellery and parts thereof", ...R0 },
  { code: "7117", desc: "Imitation jewellery", ...R0 },
  { code: "7118", desc: "Coin", ...R0 },

  // === Chapter 72-73 — Iron & Steel ===
  { code: "7201", desc: "Pig iron and spiegeleisen in pigs, blocks or forms", ...R18 },
  { code: "7204", desc: "Ferrous waste and scrap; remelting scrap ingots", ...R18 },
  { code: "7206", desc: "Iron and non-alloy steel in ingots or primary forms", ...R18 },
  { code: "7208", desc: "Flat-rolled iron/steel, hot-rolled, ≥600mm width", ...R18 },
  { code: "7209", desc: "Flat-rolled iron/steel, cold-rolled, ≥600mm", ...R18 },
  { code: "7210", desc: "Flat-rolled iron/steel, clad, plated or coated", ...R18 },
  { code: "7212", desc: "Flat-rolled iron/steel, <600mm, plated/coated", ...R18 },
  { code: "7213", desc: "Bars and rods, hot-rolled, in irregularly wound coils", ...R18 },
  { code: "7214", desc: "Other bars and rods of iron/non-alloy steel", ...R18 },
  { code: "7216", desc: "Angles, shapes and sections of iron or non-alloy steel", ...R18 },
  { code: "7217", desc: "Wire of iron or non-alloy steel", ...R18 },
  { code: "7219", desc: "Flat-rolled stainless steel, width ≥600mm", ...R18 },
  { code: "7220", desc: "Flat-rolled stainless steel, width <600mm", ...R18 },
  { code: "7222", desc: "Other bars and rods of stainless steel", ...R18 },
  { code: "7226", desc: "Flat-rolled other alloy steel, width <600mm", ...R18 },
  { code: "7301", desc: "Sheet piling of iron or steel", ...R18 },
  { code: "7302", desc: "Railway or tramway track construction material", ...R18 },
  { code: "7303", desc: "Tubes, pipes and hollow profiles, of cast iron", ...R18 },
  { code: "7304", desc: "Tubes, pipes, hollow profiles, seamless, of iron/steel", ...R18 },
  { code: "7305", desc: "Other tubes and pipes (welded), external > 406.4mm", ...R18 },
  { code: "7306", desc: "Other tubes, pipes and hollow profiles, welded/riveted", ...R18 },
  { code: "7307", desc: "Tube or pipe fittings (elbows, flanges) of iron/steel", ...R18 },
  { code: "7308", desc: "Structures and parts of structures, of iron or steel", ...R18 },
  { code: "7310", desc: "Tanks, casks, drums, cans, boxes < 300L of iron/steel", ...R18 },
  { code: "7311", desc: "Containers for compressed or liquefied gas, of iron/steel", ...R18 },
  { code: "7312", desc: "Stranded wire, ropes, cables, plaited bands of iron/steel", ...R18 },
  { code: "7314", desc: "Cloth, grill, netting and fencing, of iron or steel wire", ...R18 },
  { code: "7315", desc: "Chain and parts thereof, of iron or steel", ...R18 },
  { code: "7317", desc: "Nails, tacks, drawing pins, staples of iron/steel", ...R18 },
  { code: "7318", desc: "Screws, bolts, nuts, coach screws, washers of iron/steel", ...R18 },
  { code: "7320", desc: "Springs and leaves for springs, of iron or steel", ...R18 },
  { code: "7321", desc: "Stoves, ranges, grates, cookers, barbecues (non-electric)", ...R18 },
  { code: "7323", desc: "Table, kitchen or other household articles of iron/steel", ...R18 },
  { code: "7324", desc: "Sanitary ware and parts thereof, of iron or steel", ...R18 },
  { code: "7325", desc: "Other cast articles of iron or steel", ...R18 },
  { code: "7326", desc: "Other articles of iron or steel", ...R18 },

  // === Chapter 74-81 — Non-ferrous metals ===
  { code: "7402", desc: "Unrefined copper; copper anodes for electrolytic refining", ...R18 },
  { code: "7403", desc: "Refined copper and copper alloys, unwrought", ...R18 },
  { code: "7404", desc: "Copper waste and scrap", ...R18 },
  { code: "7407", desc: "Copper bars, rods and profiles", ...R18 },
  { code: "7408", desc: "Copper wire", ...R18 },
  { code: "7411", desc: "Copper tubes and pipes", ...R18 },
  { code: "7419", desc: "Other articles of copper", ...R18 },
  { code: "7601", desc: "Unwrought aluminium (ingots)", ...R18 },
  { code: "7604", desc: "Aluminium bars, rods and profiles", ...R18 },
  { code: "7606", desc: "Aluminium plates, sheets and strip, thickness > 0.2mm", ...R18 },
  { code: "7607", desc: "Aluminium foil, ≤ 0.2mm thickness", ...R18 },
  { code: "7608", desc: "Aluminium tubes and pipes", ...R18 },
  { code: "7615", desc: "Table, kitchen or other household articles of aluminium", ...R12 },
  { code: "7616", desc: "Other articles of aluminium", ...R18 },
  { code: "7801", desc: "Unwrought lead", ...R18 },
  { code: "7901", desc: "Unwrought zinc", ...R18 },
  { code: "8001", desc: "Unwrought tin", ...R18 },

  // === Chapter 82 — Tools ===
  { code: "8201", desc: "Hand tools: spades, shovels, mattocks, forks, rakes", ...R12 },
  { code: "8202", desc: "Hand saws; blades for saws of all kinds", ...R18 },
  { code: "8203", desc: "Files, rasps, pliers, tweezers, wire cutters", ...R18 },
  { code: "8204", desc: "Hand-operated spanners and wrenches", ...R18 },
  { code: "8205", desc: "Hand tools not elsewhere specified or included", ...R18 },
  { code: "8206", desc: "Tools of two or more of 8202 to 8205, in sets for retail", ...R18 },
  { code: "8207", desc: "Interchangeable tools for hand tools/machine tools (drill bits)", ...R18 },
  { code: "8208", desc: "Knives and cutting blades, for machines/appliances", ...R18 },
  { code: "8211", desc: "Knives with cutting blades (other than 8208)", ...R12 },
  { code: "8212", desc: "Razors and razor blades", ...R18 },
  { code: "8213", desc: "Scissors, tailors' shears and similar shears", ...R12 },
  { code: "8214", desc: "Other articles of cutlery (paper knives, manicure sets)", ...R12 },
  { code: "8215", desc: "Spoons, forks, ladles, skimmers, cake-servers", ...R12 },

  // === Chapter 83 — Metal misc ===
  { code: "8301", desc: "Padlocks and locks, clasps, keys of base metal", ...R18 },
  { code: "8302", desc: "Base metal mountings, fittings for furniture, doors", ...R18 },
  { code: "8303", desc: "Armoured or reinforced safes, strong-boxes", ...R18 },
  { code: "8304", desc: "Filing cabinets, card-index cabinets, office trays", ...R18 },
  { code: "8306", desc: "Bells, statuettes, ornaments of base metal", ...R18 },
  { code: "8308", desc: "Buckles, clasps, hooks, eyelets of base metal", ...R18 },
  { code: "8311", desc: "Wire, rods, tubes for soldering, brazing, welding", ...R18 },

  // === Chapter 84 — Machinery extras ===
  { code: "8402", desc: "Steam or other vapour generating boilers", ...R18 },
  { code: "8404", desc: "Auxiliary plant for use with boilers of 8402 or 8403", ...R18 },
  { code: "8406", desc: "Steam turbines and other vapour turbines", ...R18 },
  { code: "8407", desc: "Spark-ignition reciprocating or rotary internal combustion engines", ...R28 },
  { code: "8408", desc: "Compression-ignition internal combustion engines (diesel)", ...R28 },
  { code: "8409", desc: "Parts suitable for use with engines of 8407 or 8408", ...R28 },
  { code: "8413", desc: "Pumps for liquids; liquid elevators", ...R18 },
  { code: "8414", desc: "Air/vacuum pumps, air compressors, fans, ventilating hoods", ...R18 },
  { code: "8415", desc: "Air conditioning machines", ...R28 },
  { code: "8418", desc: "Refrigerators, freezers and other refrigerating equipment", ...R28 },
  { code: "8419", desc: "Machinery for treating materials by change of temperature", ...R18 },
  { code: "8421", desc: "Centrifuges; filtering or purifying machinery for liquids/gases", ...R18 },
  { code: "8422", desc: "Dish washing machines; packing/wrapping machinery", ...R18 },
  { code: "8423", desc: "Weighing machinery (excl. balances of 90mg sensitivity)", ...R18 },
  { code: "8424", desc: "Mechanical appliances for projecting, dispersing liquids (sprayers)", ...R18 },
  { code: "8425", desc: "Pulley tackle and hoists (other than skip hoists); winches", ...R18 },
  { code: "8426", desc: "Ships' derricks; cranes; mobile lifting frames", ...R18 },
  { code: "8427", desc: "Fork-lift trucks; other works trucks fitted with lifting/handling equipment", ...R18 },
  { code: "8429", desc: "Self-propelled bulldozers, angledozers, graders, scrapers", ...R28 },
  { code: "8432", desc: "Agricultural, horticultural or forestry machinery", ...R12 },
  { code: "8433", desc: "Harvesting or threshing machinery (combine harvesters)", ...R12 },
  { code: "8437", desc: "Machines for cleaning, sorting or grading seed, grain", ...R5 },
  { code: "8443", desc: "Printing machinery; ancillary machines", ...R18 },
  { code: "8450", desc: "Household or laundry-type washing machines", ...R18 },
  { code: "8451", desc: "Machinery for washing, cleaning, wringing textile yarn/fabrics", ...R18 },
  { code: "8452", desc: "Sewing machines (other than book-sewing machines)", ...R12 },
  { code: "8462", desc: "Machine-tools for working metal by forging, hammering", ...R18 },
  { code: "8465", desc: "Machine-tools for working wood, cork, bone, hard rubber", ...R18 },
  { code: "8467", desc: "Tools for working in the hand, pneumatic/hydraulic/motor", ...R18 },
  { code: "8470", desc: "Calculating machines; cash registers, postage-franking", ...R18 },
  { code: "8473", desc: "Parts and accessories for machines of 8470 to 8472", ...R18 },
  { code: "8474", desc: "Machinery for sorting, screening, mixing, crushing minerals", ...R18 },
  { code: "8477", desc: "Machinery for working rubber or plastics", ...R18 },
  { code: "8479", desc: "Machines and mechanical appliances n.e.c.", ...R18 },
  { code: "8481", desc: "Taps, cocks, valves for pipes, boiler shells, tanks", ...R18 },
  { code: "8482", desc: "Ball or roller bearings", ...R18 },
  { code: "8483", desc: "Transmission shafts, cranks, bearing housings, gears", ...R18 },
  { code: "8484", desc: "Gaskets and similar joints of metal sheeting", ...R18 },
  { code: "8487", desc: "Machinery parts, not containing electrical connectors", ...R18 },

  // === Chapter 85 — Electrical extras ===
  { code: "8501", desc: "Electric motors and generators (excl. generating sets)", ...R18 },
  { code: "8502", desc: "Electric generating sets and rotary converters", ...R18 },
  { code: "8503", desc: "Parts suitable for use with machines of 8501/8502", ...R18 },
  { code: "8506", desc: "Primary cells and primary batteries", ...R18 },
  { code: "8507", desc: "Electric accumulators (batteries), including separators", ...R28 },
  { code: "8508", desc: "Vacuum cleaners", ...R18 },
  { code: "8509", desc: "Electro-mechanical domestic appliances with self-contained motor", ...R18 },
  { code: "8510", desc: "Shavers, hair clippers and hair-removing appliances", ...R18 },
  { code: "8511", desc: "Electrical ignition/starting equipment for internal combustion engines", ...R28 },
  { code: "8512", desc: "Electrical lighting/signalling equipment for cycles/motor vehicles", ...R28 },
  { code: "8513", desc: "Portable electric lamps, self-contained (torches)", ...R18 },
  { code: "8514", desc: "Industrial or laboratory electric furnaces and ovens", ...R18 },
  { code: "8515", desc: "Electric (incl. electrically heated gas) welding machines", ...R18 },
  { code: "8516", desc: "Electric water heaters, hair dryers, smoothing irons", ...R18 },
  { code: "8518", desc: "Microphones, loudspeakers, headphones, audio amplifiers", ...R18 },
  { code: "8519", desc: "Sound recording or reproducing apparatus", ...R18 },
  { code: "8521", desc: "Video recording or reproducing apparatus", ...R18 },
  { code: "8523", desc: "Discs, tapes, solid-state non-volatile storage devices", ...R18 },
  { code: "8525", desc: "Transmission apparatus for radio, television, cameras", ...R18 },
  { code: "8526", desc: "Radar apparatus, radio navigational aid, remote control", ...R18 },
  { code: "8527", desc: "Reception apparatus for radio-broadcasting", ...R18 },
  { code: "8528", desc: "Monitors and projectors; reception apparatus for television", ...R28 },
  { code: "8531", desc: "Electric sound or visual signalling apparatus (bells, alarms)", ...R18 },
  { code: "8532", desc: "Electrical capacitors, fixed, variable or adjustable", ...R18 },
  { code: "8533", desc: "Electrical resistors (incl. rheostats and potentiometers)", ...R18 },
  { code: "8534", desc: "Printed circuits", ...R18 },
  { code: "8535", desc: "Electrical apparatus for switching or protecting > 1000V", ...R18 },
  { code: "8536", desc: "Electrical apparatus for switching or protecting ≤ 1000V", ...R18 },
  { code: "8537", desc: "Boards, panels for electric control or distribution", ...R18 },
  { code: "8538", desc: "Parts suitable for use with the apparatus of 8535-8537", ...R18 },
  { code: "8539", desc: "Electric filament or discharge lamps, LED lamps", ...R12 },
  { code: "8540", desc: "Thermionic, cold cathode or photo-cathode valves and tubes", ...R18 },
  { code: "8541", desc: "Semiconductor devices; LEDs; mounted piezo-electric crystals", ...R18 },
  { code: "8542", desc: "Electronic integrated circuits (ICs)", ...R18 },
  { code: "8543", desc: "Electrical machines and apparatus, having individual functions", ...R18 },
  { code: "8544", desc: "Insulated wire, cable and other insulated electric conductors", ...R18 },
  { code: "8545", desc: "Carbon electrodes, carbon brushes, lamp carbons, battery carbons", ...R18 },
  { code: "8546", desc: "Electrical insulators of any material", ...R18 },
  { code: "8547", desc: "Insulating fittings for electrical machines/appliances", ...R18 },

  // === Chapter 86-89 — Vehicles ===
  { code: "8601", desc: "Rail locomotives powered from external source of electricity", ...R5 },
  { code: "8603", desc: "Self-propelled railway or tramway coaches, vans", ...R5 },
  { code: "8607", desc: "Parts of railway or tramway locomotives or rolling-stock", ...R18 },
  { code: "8701", desc: "Tractors (other than tractors of 8709)", ...R12 },
  { code: "8702", desc: "Motor vehicles for transport of 10 or more persons (buses)", ...R28 },
  { code: "8703", desc: "Motor cars and other motor vehicles for transport of persons", ...R28 },
  { code: "8704", desc: "Motor vehicles for the transport of goods (trucks)", ...R28 },
  { code: "8705", desc: "Special purpose motor vehicles (breakdown lorries, cranes)", ...R28 },
  { code: "8706", desc: "Chassis fitted with engines, for the motor vehicles 8701-8705", ...R28 },
  { code: "8707", desc: "Bodies (including cabs) for the motor vehicles 8701-8705", ...R28 },
  { code: "8708", desc: "Parts and accessories of the motor vehicles 8701-8705", ...R28 },
  { code: "8711", desc: "Motorcycles (incl. mopeds) and cycles with auxiliary motor", ...R28 },
  { code: "8712", desc: "Bicycles and other cycles (incl. delivery tricycles)", ...R12 },
  { code: "8713", desc: "Carriages for disabled persons", ...R5 },
  { code: "8716", desc: "Trailers and semi-trailers; other vehicles, not mechanically propelled", ...R18 },
  { code: "8802", desc: "Other aircraft (helicopters, aeroplanes); spacecraft", ...R5 },
  { code: "8903", desc: "Yachts and other vessels for pleasure or sports; rowing boats", ...R28 },

  // === Chapter 90 — Optical, measuring, medical ===
  { code: "9001", desc: "Optical fibres and optical fibre bundles; lenses (unmounted)", ...R18 },
  { code: "9002", desc: "Lenses, prisms, mirrors and other optical elements, mounted", ...R18 },
  { code: "9003", desc: "Frames and mountings for spectacles, goggles", ...R18 },
  { code: "9005", desc: "Binoculars, monoculars, other optical telescopes", ...R18 },
  { code: "9006", desc: "Photographic cameras (other than cinematographic)", ...R18 },
  { code: "9008", desc: "Image projectors, other than cinematographic", ...R18 },
  { code: "9013", desc: "Liquid crystal devices; lasers (other than laser diodes)", ...R18 },
  { code: "9015", desc: "Surveying, hydrographic, oceanographic instruments", ...R18 },
  { code: "9017", desc: "Drawing, marking-out, mathematical calculating instruments", ...R12 },
  { code: "9018", desc: "Instruments and appliances used in medical, surgical, dental", ...R12 },
  { code: "9019", desc: "Mechano-therapy appliances; massage apparatus", ...R12 },
  { code: "9020", desc: "Other breathing appliances and gas masks", ...R12 },
  { code: "9022", desc: "Apparatus based on the use of X-rays or of alpha/beta/gamma", ...R12 },
  { code: "9024", desc: "Machines for testing hardness, strength, compressibility", ...R18 },
  { code: "9026", desc: "Instruments for measuring/checking the flow, level, pressure", ...R18 },
  { code: "9027", desc: "Instruments and apparatus for physical or chemical analysis", ...R18 },
  { code: "9029", desc: "Revolution counters, taximeters, speedometers, tachometers", ...R18 },
  { code: "9030", desc: "Oscilloscopes, spectrum analysers, other instruments for electric", ...R18 },
  { code: "9031", desc: "Measuring or checking instruments, appliances and machines n.e.c.", ...R18 },
  { code: "9032", desc: "Automatic regulating or controlling instruments and apparatus", ...R18 },

  // === Chapter 91-92 — Clocks, musical instruments ===
  { code: "9101", desc: "Wrist-watches, pocket-watches, other watches (precious metal case)", ...R18 },
  { code: "9102", desc: "Wrist-watches, pocket-watches, other watches (other than 9101)", ...R18 },
  { code: "9105", desc: "Other clocks (alarm clocks, wall clocks)", ...R18 },
  { code: "9202", desc: "Other string musical instruments (guitars, violins)", ...R18 },
  { code: "9205", desc: "Wind musical instruments (organs, harmoniums, flutes)", ...R18 },
  { code: "9207", desc: "Musical instruments, the sound is produced electrically", ...R18 },

  // === Chapter 93 — Arms ===
  { code: "9302", desc: "Revolvers and pistols", ...R18 },
  { code: "9303", desc: "Other firearms and similar devices operated by explosion", ...R18 },
  { code: "9304", desc: "Other arms (air guns, spring guns) other than 9307", ...R18 },

  // === Chapter 94 — Furniture ===
  { code: "9402", desc: "Medical, surgical, dental or veterinary furniture", ...R18 },
  { code: "9403", desc: "Other furniture and parts thereof", ...R18 },
  { code: "9406", desc: "Prefabricated buildings", ...R18 },

  // === Chapter 95 — Toys, sports ===
  { code: "9501", desc: "Wheeled toys designed to be ridden by children", ...R12 },
  { code: "9502", desc: "Dolls representing only human beings", ...R12 },
  { code: "9503", desc: "Other toys; reduced-size models; puzzles", ...R12 },
  { code: "9504", desc: "Video game consoles and machines, articles for funfair", ...R28 },
  { code: "9505", desc: "Festive, carnival or other entertainment articles", ...R12 },
  { code: "9507", desc: "Fishing rods, fish-hooks and other line fishing tackle", ...R12 },
  { code: "9508", desc: "Roundabouts, swings, shooting galleries, travelling circuses", ...R28 },

  // === Chapter 96 — Miscellaneous manufactured ===
  { code: "9601", desc: "Worked ivory, bone, tortoise-shell, horn, coral", ...R12 },
  { code: "9602", desc: "Worked vegetable/mineral carving material; moulded articles", ...R18 },
  { code: "9604", desc: "Hand sieves and hand riddles", ...R18 },
  { code: "9605", desc: "Travel sets for personal toilet, sewing", ...R18 },
  { code: "9606", desc: "Buttons, press-fasteners, snap-fasteners, button moulds", ...R18 },
  { code: "9607", desc: "Slide fasteners and parts thereof (zippers)", ...R18 },
  { code: "9610", desc: "Slates and boards, with writing or drawing surfaces", ...R12 },
  { code: "9612", desc: "Typewriter or similar ribbons, inked; ink-pads", ...R18 },
  { code: "9613", desc: "Cigarette lighters and other lighters", ...R18 },
  { code: "9615", desc: "Combs, hair-slides and the like; hairpins, curling pins", ...R18 },
  { code: "9616", desc: "Scent sprays, powder-puffs, pads for cosmetics", ...R18 },
  { code: "9617", desc: "Vacuum flasks and other vacuum vessels, complete with cases", ...R18 },
  { code: "9619", desc: "Sanitary towels and tampons, napkins and napkin liners", ...R12 },

  // === Chapter 97 — Works of art ===
  { code: "9701", desc: "Paintings, drawings and pastels, executed entirely by hand", ...R12 },
  { code: "9702", desc: "Original engravings, prints and lithographs", ...R12 },
  { code: "9703", desc: "Original sculptures and statuary, in any material", ...R12 },
  { code: "9705", desc: "Collections and collectors' pieces of zoological, botanical", ...R12 },
  { code: "9706", desc: "Antiques of an age exceeding 100 years", ...R12 },

  // === Additional SAC — Construction, transport, hospitality ===
  { code: "995411", desc: "Construction services of single dwelling residential building", ...R18 },
  { code: "995412", desc: "Construction of multi-dwelling / multi-storeyed residential building", ...R18 },
  { code: "995421", desc: "General construction services of highways, streets, roads", ...R18 },
  { code: "995432", desc: "Site preparation services (excavation, earth-moving)", ...R18 },
  { code: "995461", desc: "Electrical installation services", ...R18 },
  { code: "995462", desc: "Water plumbing and drain laying services", ...R18 },
  { code: "995463", desc: "Heating, ventilation and air conditioning installation", ...R18 },
  { code: "995471", desc: "Glazing services (glass installation)", ...R18 },
  { code: "995472", desc: "Plastering services", ...R18 },
  { code: "995473", desc: "Painting services", ...R18 },
  { code: "995474", desc: "Floor and wall tiling services", ...R18 },
  { code: "996111", desc: "Services provided for a fee/commission by wholesale trade agents", ...R18 },
  { code: "996211", desc: "Retail trade services on a fee/commission basis", ...R18 },
  { code: "996311", desc: "Room or unit accommodation services provided by hotels", ...R12 },
  { code: "996331", desc: "Services provided by restaurants, cafés (non-AC, non-alcohol)", ...R5 },
  { code: "996332", desc: "Services provided by restaurants, cafés (AC or alcohol)", ...R5 },
  { code: "996334", desc: "Catering services in exhibition halls, marriage halls", ...R18 },
  { code: "996411", desc: "Local land transport services of passengers by road (taxi)", ...R5 },
  { code: "996419", desc: "Other land transport services of passengers", ...R5 },
  { code: "996422", desc: "Long-distance land transport services of passengers", ...R5 },
  { code: "996511", desc: "Road transport of goods (GTA), letters, parcels", ...R5 },
  { code: "996531", desc: "Air transport services of goods", ...R18 },
  { code: "996601", desc: "Rental services of transport vehicles with operators", ...R18 },
  { code: "996713", desc: "Clearing and forwarding services", ...R18 },
  { code: "996719", desc: "Other cargo and mail transport support services", ...R18 },
  { code: "996729", desc: "Other supporting transport services", ...R18 },
  { code: "997111", desc: "Central banking services", ...R18 },
  { code: "997112", desc: "Deposit services (banks accepting deposits)", ...R18 },
  { code: "997113", desc: "Credit-granting services (loans, overdrafts)", ...R18 },
  { code: "997114", desc: "Financial leasing services", ...R18 },
  { code: "997120", desc: "Investment banking services", ...R18 },
  { code: "997131", desc: "Pension services", ...R18 },
  { code: "997133", desc: "Motor vehicle insurance services", ...R18 },
  { code: "997134", desc: "Marine, aviation, and other transport insurance", ...R18 },
  { code: "997135", desc: "Freight insurance services", ...R18 },
  { code: "997136", desc: "Other property insurance services", ...R18 },
  { code: "997139", desc: "Other non-life insurance services (excl. reinsurance)", ...R18 },
  { code: "997141", desc: "Reinsurance services", ...R18 },
  { code: "997152", desc: "Brokerage and related securities services", ...R18 },
  { code: "997159", desc: "Other services auxiliary to financial services", ...R18 },
  { code: "998211", desc: "Legal advisory and representation services", ...R18 },
  { code: "998221", desc: "Financial auditing services", ...R18 },
  { code: "998222", desc: "Accounting and bookkeeping services", ...R18 },
  { code: "998223", desc: "Tax consultancy and preparation services", ...R18 },
  { code: "998231", desc: "Corporate tax consulting and preparation services", ...R18 },
  { code: "998321", desc: "Architectural advisory services", ...R18 },
  { code: "998332", desc: "Architectural services for residential building projects", ...R18 },
  { code: "998341", desc: "Geological and geophysical consulting services", ...R18 },
  { code: "998343", desc: "Mineral exploration and evaluation", ...R18 },
  { code: "998363", desc: "Sale of advertising space in print media", ...R5 },
  { code: "998365", desc: "Sale of internet advertising space", ...R18 },
  { code: "998371", desc: "Photography services (portrait, wedding, event)", ...R18 },
  { code: "998391", desc: "Specialty design services", ...R18 },
  { code: "998431", desc: "Online text-based information (news, journals) services", ...R18 },
  { code: "998432", desc: "Online audio content services", ...R18 },
  { code: "998433", desc: "Online video content services", ...R18 },
  { code: "998434", desc: "Online gaming services", ...R28 },
  { code: "998511", desc: "Executive/retained personnel search services", ...R18 },
  { code: "998513", desc: "Contract staffing services", ...R18 },
  { code: "998531", desc: "General cleaning services", ...R18 },
  { code: "998532", desc: "Specialised cleaning services", ...R18 },
  { code: "998551", desc: "Reservation services for transportation", ...R18 },
  { code: "998552", desc: "Reservation services for accommodation, cruises, package tours", ...R18 },
  { code: "998553", desc: "Reservation services for convention centres, congress halls", ...R18 },
  { code: "998554", desc: "Reservation services for event tickets, entertainment", ...R18 },
  { code: "998719", desc: "Maintenance and repair services of other machinery", ...R18 },
  { code: "998722", desc: "Repair services of watches, clocks and jewellery", ...R18 },
  { code: "998723", desc: "Repair services of garments and household textiles", ...R18 },
  { code: "998729", desc: "Maintenance and repair services of other goods n.e.c.", ...R18 },
  { code: "999211", desc: "Compulsory social security services", ...R0 },
  { code: "999311", desc: "Inpatient services (hospital admissions)", ...R0 },
  { code: "999312", desc: "Medical and dental services (outpatient)", ...R0 },
  { code: "999313", desc: "Childbirth and related services", ...R0 },
  { code: "999319", desc: "Other human health services", ...R0 },
  { code: "999321", desc: "Residential health-care services other than by hospitals", ...R0 },
  { code: "999333", desc: "Vocational rehabilitation services", ...R0 },
  { code: "999411", desc: "Pre-primary education services", ...R0 },
  { code: "999421", desc: "Primary education services", ...R0 },
  { code: "999431", desc: "Secondary education services (general)", ...R0 },
  { code: "999441", desc: "Higher education services (general/technical/vocational)", ...R0 },
  { code: "999511", desc: "Sewage and sewerage treatment services", ...R18 },
  { code: "999521", desc: "General waste collection services (non-hazardous)", ...R18 },
  { code: "999611", desc: "Services of performing artists", ...R18 },
  { code: "999612", desc: "Services of authors, composers, sculptors, other artists", ...R18 },
  { code: "999631", desc: "Museum and preservation services of historical sites", ...R18 },
  { code: "999651", desc: "Sports and recreational sports event promotion services", ...R18 },
  { code: "999691", desc: "Religious services", ...R0 },
  { code: "999731", desc: "Membership services of business, employers, professional org.", ...R18 },
  { code: "999799", desc: "Other services n.e.c.", ...R18 },
];
