REVOKE EXECUTE ON FUNCTION public._require_admin(uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public._require_admin(uuid, text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public._require_admin_password(uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public._require_admin_password(uuid, text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.can_write_company(uuid, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.can_write_company(uuid, uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.change_account_password(uuid, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.change_account_password(uuid, text, text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.create_app_user(uuid, text, text, app_user_role, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.create_app_user(uuid, text, text, app_user_role, text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.delete_account_admin(uuid, text, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.delete_account_admin(uuid, text, uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.delete_app_user(uuid, text, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.delete_app_user(uuid, text, uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.delete_import_batch(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.delete_import_batch(uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.delete_vouchers_bulk(uuid, voucher_type, date, date) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.delete_vouchers_bulk(uuid, voucher_type, date, date) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.has_company_role(uuid, uuid, company_role) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.has_company_role(uuid, uuid, company_role) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.is_company_member(uuid, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.is_company_member(uuid, uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.is_period_locked(uuid, date) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.is_period_locked(uuid, date) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.list_accounts_admin(uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.list_accounts_admin(uuid, text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.lock_period(uuid, text, text, date, date, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.lock_period(uuid, text, text, date, date, text, text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.next_voucher_number(uuid, voucher_type) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.next_voucher_number(uuid, voucher_type) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.reclassify_misposted_vouchers(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.reclassify_misposted_vouchers(uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.recompute_monthly_balances(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.recompute_monthly_balances(uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.repair_orphan_vouchers_with_suspense(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.repair_orphan_vouchers_with_suspense(uuid) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.reset_app_user_pin(uuid, text, uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.reset_app_user_pin(uuid, text, uuid, text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.save_voucher_atomic(jsonb, jsonb, jsonb) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.save_voucher_atomic(jsonb, jsonb, jsonb) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.set_company_password(uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.set_company_password(uuid, text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.sync_opening_balances_from_previous_fy(uuid, date) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.sync_opening_balances_from_previous_fy(uuid, date) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.unlock_period(uuid, text, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.unlock_period(uuid, text, text, text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.update_account_admin(uuid, text, uuid, text, app_user_role, boolean, boolean, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.update_account_admin(uuid, text, uuid, text, app_user_role, boolean, boolean, text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.verify_company_password(uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.verify_company_password(uuid, text) TO authenticated, service_role;
REVOKE EXECUTE ON FUNCTION public.voucher_company_id(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.voucher_company_id(uuid) TO authenticated, service_role;