export const Constants = {
    public: {
        Enums: {
            app_user_role: ["admin", "staff"],
            company_role: ["admin", "accountant", "viewer"],
            entity_status: [
                "individual",
                "huf",
                "aop",
                "pvt_ltd",
                "registered_firm",
                "trust",
            ],
            gst_treatment: [
                "regular",
                "composition",
                "unregistered",
                "consumer",
                "sez_with_payment",
                "sez_without_payment",
                "overseas",
                "deemed_export",
                "uin_holder",
            ],
            itc_class: [
                "inputs",
                "capital_goods",
                "input_services",
                "ineligible",
                "na",
            ],
            ledger_type: [
                "sundry_debtor",
                "sundry_creditor",
                "cash",
                "bank",
                "expense_direct",
                "expense_indirect",
                "income_direct",
                "income_indirect",
                "fixed_asset",
                "current_asset",
                "current_liability",
                "loan_liability",
                "capital",
                "duties_taxes",
                "stock_in_hand",
            ],
            supply_nature: [
                "taxable",
                "zero_rated_wp",
                "zero_rated_wop",
                "nil_rated",
                "exempt",
                "non_gst",
                "rcm_inward",
                "deemed_export",
            ],
            voucher_type: [
                "sales",
                "purchase",
                "receipt",
                "payment",
                "journal",
                "contra",
                "credit_note",
                "debit_note",
                "quotation",
                "sales_order",
                "delivery_note",
                "manufacturing",
            ],
        },
    },
};
